// Van #1 demo route for today, shared by the groomer app and the demo iCal feed (server.ts).
export const DEMO_ROUTE_STOPS = [
  {
    time: "8:30 AM",
    pet: "Luna",
    breed: "Maltese",
    svc: "Full Spa",
    status: "Completed",
    code: "9142",
    address: "88 Broadway Ave, Unit 1402, Toronto M4P 1V6",
    phone: "416-555-0142",
    notes: "Concierge notified at front desk. Lockbox on bicycle rack in P1 parking (code 9142). Please ensure harness is snug.",
    waiver: "Signed digitally (Fear-Free Handling)",
  },
  {
    time: "10:00 AM",
    pet: "Bentley",
    breed: "Goldendoodle",
    svc: "Teddy Cut",
    status: "Completed",
    code: "4821",
    address: "142 Roehampton Ave, Toronto M4P 1R4",
    phone: "416-555-0199",
    notes: "Enter through side wooden gate (keypad 4821). Bentley will be in sunroom. Please make sure indoor cat Jasper does not slip out.",
    waiver: "Signed digitally (Matted Shavedown Waiver)",
  },
  {
    time: "11:45 AM",
    pet: "Oscar",
    breed: "French Bulldog",
    svc: "Bath & Tidy",
    status: "En Route",
    code: "3390",
    address: "180 University Ave (Shangri-La Residences), Toronto M5H 0A2",
    phone: "416-555-0211",
    notes: "Visitor loop parking authorized with security. Digital smart lock code is 3390#. Oscar loves head rubs before stepping into van.",
    waiver: "Signed digitally (Brachycephalic Care)",
  },
  {
    time: "1:30 PM",
    pet: "Maple",
    breed: "Golden Retriever",
    svc: "De-Shed Spa",
    status: "Next",
    code: "7105",
    address: "45 Roxborough St E, Rosedale M4W 1V5",
    phone: "416-555-0374",
    notes: "Garage keypad code 7105. Leash hanging on hook next to mudroom door. Blueberry facial authorized.",
    waiver: "Signed digitally (Full Spa Waiver)",
  },
  {
    time: "3:15 PM",
    pet: "Pip",
    breed: "Shih Tzu",
    svc: "Full Spa",
    status: "Pending",
    code: "1628",
    address: "320 Brunswick Ave, The Annex M5S 2M7",
    phone: "416-555-0455",
    notes: "Lockbox code 1628 on rear deck railing. Treats in kitchen bowl if Pip is shy when meeting groomer.",
    waiver: "Signed digitally (Senior Dog Care)",
  },
] as const;
